site_name: База знаний - социальная инженерия
site_description: Систематизированная баа знаний в предметной области социальной инженерии
site_author: Иван Влас
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: ru
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Темная тема
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Светлая тема
      primary: teal
      accent: lime

nav:
  - Домашняя страница: index.md
  - Угрозы безопасности: 
    - Начало: threats/begin.md
    - Страница 1: threats/page1.md
    - Страница 2: threats/page2.md
    - Страница 3: threats/page3.md
    - Страница 4: threats/page4.md
    - Страница 5: threats/page5.md
    - Страница 6: threats/page6.md
  - Уязвимости: 
    - Начало: vulnerabilities/begin.md
    - Страница 1: vulnerabilities/page1.md
    - Страница 2: vulnerabilities/page2.md
    - Страница 3: vulnerabilities/page3.md
    - Страница 4: vulnerabilities/page4.md
    - Страница 5: vulnerabilities/page5.md
    - Страница 6: vulnerabilities/page6.md
  - Меры защиты:
    - Начало: measures/begin.md 
    - Страница 1: measures/page1.md
    - Страница 2: measures/page2.md
    - Страница 3: measures/page3.md
    - Страница 4: measures/page4.md
    - Страница 5: measures/page5.md
    - Страница 6: measures/page6.md    
  - Глоссарий: glossary.md

extra: 
  generator: false